include:
  - rainmaker/core/branch/v1_0
  - .mariadb
  - .mariadb/drupal
  - .mariadb/mysqltuner
  - .apache
  - .apache/drupal
  - .memcached
  - .php5
  - .php5/uploadprogress
  - .php5/drupal
  - .java7
  - .tomcat7
  - .tomcat7/solr
  - .tomcat7/solr/drupal
  - .drush
  - .composer
